const Coal = new Item("Coal", "Material", 99)
const IronOre = new Item("IronOre", "Material", 99)
const IronBar = new Item("IronBar", "Material", 99)
const CopperOre = new Item("CopperOre", "Material", 99)
const Oil = new Item("Oil", "Material", 99)
const CompressedOil = new Item("CompressedOil", "Material", 99)
